# Generated by Django 6.0.3 on 2026-05-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='end_page',
            field=models.PositiveIntegerField(default=1, verbose_name='End Page'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='start_page',
            field=models.PositiveIntegerField(default=1, verbose_name='Start Page'),
        ),
    ]
